Fix appendToJson function when value is a const char*
reo7sp/tgbot-cpp pull request #154
Opened 2020-10-22 20:26 UTC by nesc1

2020-10-29 03:28 UTC, JellyBrick requested changes

2020-10-29 03:28 UTC, JellyBrick commented on include/tgbot/TgTypeParser.h
> +        }
```suggestion
        if (value != nullptr){
            std::string strValue(value);
            appendToJson(json, varName, strValue);
        }
```

2020-10-29 11:13 UTC, JellyBrick approved these changes

2020-10-31 23:18 UTC, reo7sp commented
CI checks failed. https://travis-ci.org/github/reo7sp/tgbot-cpp/builds/739867367

GCC log:
```
In file included from /usr/src/tgbot-cpp/include/tgbot/Api.h:4:0,
                 from /usr/src/tgbot-cpp/src/Api.cpp:1:
/usr/src/tgbot-cpp/include/tgbot/TgTypeParser.h:504:17: error: 'void TgBot::TgTypeParser::appendToJson(std::__cxx11::string&, const string&, const char*) const' cannot be overloaded
     inline void appendToJson(std::string& json, const std::string& varName, const char *value) const { appendToJson(json, varName, std::string(value)); }
                 ^~~~~~~~~~~~
/usr/src/tgbot-cpp/include/tgbot/TgTypeParser.h:497:17: error: with 'void TgBot::TgTypeParser::appendToJson(std::__cxx11::string&, const string&, const char*) const'
     inline void appendToJson(std::string& json, const std::string& varName, const char* value) const {
                 ^~~~~~~~~~~~
In file included from /usr/src/tgbot-cpp/include/tgbot/Api.h:4:0,
                 from /usr/src/tgbot-cpp/include/tgbot/Bot.h:4,
                 from /usr/src/tgbot-cpp/src/Bot.cpp:2:
/usr/src/tgbot-cpp/include/tgbot/TgTypeParser.h:504:17: error: 'void TgBot::TgTypeParser::appendToJson(std::__cxx11::string&, const string&, const char*) const' cannot be overloaded
     inline void appendToJson(std::string& json, const std::string& varName, const char *value) const { appendToJson(json, varName, std::string(value)); }
                 ^~~~~~~~~~~~
/usr/src/tgbot-cpp/include/tgbot/TgTypeParser.h:497:17: error: with 'void TgBot::TgTypeParser::appendToJson(std::__cxx11::string&, const string&, const char*) const'
     inline void appendToJson(std::string& json, const std::string& varName, const char* value) const {
                 ^~~~~~~~~~~~
```

2020-11-01 06:30 UTC, JellyBrick commented on include/tgbot/TgTypeParser.h
>      inline void appendToJson(std::string& json, const std::string& varName, const char *value) const { appendToJson(json, varName, std::string(value)); }
```suggestion

```

2020-11-01 06:31 UTC, JellyBrick requested changes

2020-11-01 06:31 UTC, JellyBrick commented on include/tgbot/TgTypeParser.h
>      inline void appendToJson(std::string& json, const std::string& varName, const char *value) const { appendToJson(json, varName, std::string(value)); }
```suggestion
```

2020-11-10 16:01 UTC, reo7sp commented
OK

2020-11-10 16:01 UTC, merged