add example project_bot
reo7sp/tgbot-cpp pull request #201
Opened 2022-06-03 16:11 UTC by dan4ik605743

I wrote a bot that can send weather and exchange rates based on your library for working with api telegram, don't you want it to be in the example? Perhaps people seeing it would be easier to work with this library.

2022-06-03 20:41 UTC, reo7sp requested changes
Commit this example in samples directory directly, not via submodule

2022-06-04 03:46 UTC, dan4ik605743 commented
> Commit this example in samples directory directly, not via submodule

So the code will change, for example, right now I have several commits that are not ready that add inline-keyboard through a separate compilation flag, maybe it's better to let it be a submodule, how to fix it.

2022-06-04 16:06 UTC, reo7sp commented
No, sample must be complete and committed

2022-06-05 15:39 UTC, dan4ik605743 commented
> 



> No, sample must be complete and committed

Well, this is considered as a project rather than an example, but I would like to place it somewhere for you, as an example. People who would like to use this library and do not know where to start, it would certainly help and, in general, how their ideas can be implemented. Therefore, I don’t know, you can place it not in samples, in README.md give a link to the repository there is an exemplary project, what do you say? Because I'm improving the code / adding something new. So I can't copy all the files to samples/.

2022-06-05 15:46 UTC, dan4ik605743 commented
what do you say?

2022-06-05 15:47 UTC, dan4ik605743 commented
I want to help people who decide to use this library, to make some kind of contribution.

2022-06-05 16:11 UTC, reo7sp commented
Extract from your project some isolated and simple code and commit this as an sample.

Sample as a huge project would be hard to understand, that’s why it won’t be useful for people. Sample should be clear, small and easy to compile

2022-06-06 08:15 UTC, dan4ik605743 commented
something simple cannot be singled out from the whole project, everything is connected with each other. I can make one example with which it would be easier, now I will write.

2022-06-06 08:31 UTC, dan4ik605743 commented
I would like to add this example. what do you say?

2022-06-08 13:31 UTC, reo7sp requested changes

2022-06-08 13:31 UTC, reo7sp commented on samples/received-text-processing/src/main.cpp
> +    });
Let long_poll.start() be invoked only in the main loop.

```suggestion
    bool test_text_state = false;

    Bot bot(token);
    TgLongPoll long_poll(bot);

    bot.getEvents().onCommand("start", [&bot](Message::Ptr message) {
        bot.getApi().sendMessage(message->chat->id, "Hi!");
    });

    bot.getEvents().onCommand("test", [&](Message::Ptr message) {
        bot.getApi().sendMessage(message->chat->id, "Enter text");
        test_text_state = true;
    });

    bot.getEvents().onAnyMessage([&](TgBot::Message::Ptr message) {
        if (test_text_state) {
            bot.getApi().sendMessage(message->chat->id, message->text);
            test_text_state = false;
            return;
        }

        for (const auto& command : bot_commands) {
            if ("/" + command == message->text) {
                return;
            }
        }

        bot.getApi().sendMessage(message->chat->id, "unknown command");
    });
```

2022-06-08 17:17 UTC, dan4ik605743 commented on samples/received-text-processing/src/main.cpp
> +    });
? you have now changed the code it will not work as it should.

2022-06-08 17:18 UTC, dan4ik605743 commented on samples/received-text-processing/src/main.cpp
> +    });
the point of all this is the second call to long_poll to get the text from the X input.

2022-06-10 05:30 UTC, dan4ik605743 commented
@reo7sp done

2022-06-10 05:37 UTC, closed without merging

2022-06-10 05:38 UTC, dan4ik605743 commented
i rename branch