add sample
reo7sp/tgbot-cpp pull request #202
Opened 2022-06-10 05:42 UTC by dan4ik605743

https://github.com/reo7sp/tgbot-cpp/pull/201

2022-06-10 22:41 UTC, reo7sp requested changes

2022-06-10 22:41 UTC, reo7sp commented on samples/received-text-processing/Dockerfile
> +WORKDIR /usr/src/tgbot-cpp/samples/received-text-processing
I have said that build step should be appended to Dockerfile_test file, not made to seperate Dockerfile.

Look at the GitHub CI config https://github.com/reo7sp/tgbot-cpp/blob/master/.github/workflows/docker-image.yml#L18 and you see what CI does

2022-06-11 11:18 UTC, dan4ik605743 commented on samples/received-text-processing/Dockerfile
> +WORKDIR /usr/src/tgbot-cpp/samples/received-text-processing
ok

2022-06-11 11:20 UTC, dan4ik605743 commented
so?

2022-06-11 20:14 UTC, reo7sp approved these changes

2022-06-11 20:14 UTC, merged