PropertyTree set default-value
reo7sp/tgbot-cpp pull request #266
Opened 2023-03-17 09:26 UTC by YaDanilamaster

По обозначенной ранее проблеме с проблемой подтверждения платежа https://github.com/reo7sp/tgbot-cpp/discussions/265
В  файле TgTypeParser.cpp указал значения по умолчанию при парсинге Property Tree, местами они не были пропущены, ну и явно указал типы, там где они были пропущены. После чего протестировал на нескольких платежах, ошибки больше нет.

2023-05-05 17:03 UTC, JellyBrick requested changes

2023-05-05 17:03 UTC, JellyBrick commented on include/tgbot/EventBroadcaster.h
> +    inline void SetToken(std::string& botId) const {
Use `camelCase` instead of `PascalCase`

2023-05-10 20:28 UTC, reo7sp requested changes

2023-05-10 20:28 UTC, reo7sp commented on .gitignore
> +/CMakeLists.txt
Не, CMakeLists.txt ведь нужен для сборки

2024-06-10 21:43 UTC, closed without merging